# Generated by Django 4.1.1 on 2022-09-24 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256, null=True)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('event_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256, null=True)),
                ('target_amt', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='fundraising.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledged_dt', models.DateTimeField()),
                ('fullfilled', models.BooleanField()),
                ('pledged_amt', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='fundraising.campaignitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256, null=True)),
                ('goal_amt', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='fundraising.campaign')),
            ],
        ),
    ]
