# Generated by Django 4.1.1 on 2022-09-24 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempledge',
            old_name='fullfilled',
            new_name='fulfilled',
        ),
        migrations.AlterField(
            model_name='campaignitem',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_campaign', to='fundraising.campaign'),
        ),
        migrations.AlterField(
            model_name='itempledge',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pledge_item', to='fundraising.campaignitem'),
        ),
        migrations.AlterField(
            model_name='itempledge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pledge_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
